import pygame

FPS = 60

BOARD_REVEAL = pygame.USEREVENT + 1
BOARD_FLAG = pygame.USEREVENT + 2
TIMER_TICK = pygame.USEREVENT + 3
BOARD_FLAG_PLACED = pygame.USEREVENT + 4
BOARD_FLAG_REMOVED = pygame.USEREVENT + 5

MOUSEBUTTONLEFT = 1
MOUSEBUTTONMIDDLE = 2
MOUSEBUTTONRIGHT = 3
